Enable point-in-time recovery for dynamodb table.
trussworks/terraform-aws-bootstrap pull request #54
Opened 2021-06-30 18:06 UTC by chrisgilmerproj

When using `tfsec` to analyze this code it comes back with this warning:

```

      42 | # Terraform state locking
      43 | #
      44 | 
      45 | resource "aws_dynamodb_table" "terraform_state_lock" {
      46 |   name           = var.dynamodb_table_name
      47 |   hash_key       = "LockID"
      48 |   read_capacity  = 2
      49 |   write_capacity = 2
      50 | 
      51 |   server_side_encryption {
      52 |     enabled = true
      53 |   }
      54 | 
      55 |   attribute {
      56 |     name = "LockID"
      57 |     type = "S"
      58 |   }
      59 | 
      60 |   tags = var.dynamodb_table_tags
      61 | }
      62 | 

  Impact:     Accidental or malicious writes and deletes can't be rolled back
  Resolution: Enable point in time recovery

  https://tfsec.dev/docs/aws/AWS086/ 
  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point_in_time_recovery 
  https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.html 
```

The fix is simple and feels like a good default for folks.

2021-06-30 18:07 UTC, chrisgilmerproj commented
@dynamike @eeeady - could I get a review on this one?

2021-06-30 21:13 UTC, dynamike commented
Let me chat around with folks on this. My initial reaction is we don't really care about the data as they are only ephemeral locks and can't really picture a need to do a real recovery.

2021-06-30 22:13 UTC, chrisgilmerproj commented
I agree, this doesn't really move the needle. The `tfsec` tool is fickle and its hard to ignore problems in modules as dependencies. Alternatively we can make this a var and let folks choose if they care. I'm not sure the cost is a big issue here given that the scale of usage.

2021-07-13 23:08 UTC, dynamike commented
A conditional variable is one option. I would also be okay with adding a tfsec specific annotation with a comment describing why the finding is not applicable for this use case.

2021-07-14 16:17 UTC, chrisgilmerproj commented
@dynamike - I've taken both of your suggestions here. There is now a variable to let folks choose for themselves but it defaults to `false` which was the old behavior. I've also added an explicit ignore for the tfsec rule.

I'm not sure why I can't get the checks to pass but it might be a ghactions issue on my repo's end for the fork. Let me know if I need to do something about it.

2021-07-15 22:40 UTC, dynamike requested changes

2021-07-15 22:40 UTC, dynamike commented on main.tf
> +#tfsec:ignore:AWS086
Can you add a bit more context on why we would be disabling the AWS086 finding?

2021-07-15 22:40 UTC, dynamike commented on variables.tf
> +variable "point_in_time_recovery" {
To make it clear we are enabling point in time recovery for dynamodb
```suggestion 
variable "dynamodb_point_in_time_recovery" {
```

2021-07-15 22:40 UTC, dynamike commented on main.tf
> +    enabled = var.point_in_time_recovery
```suggestion
    enabled = var.dynamodb_point_in_time_recovery
```

2021-07-15 22:41 UTC, dynamike commented
For the GH actions permission error, there should be a setting to enable the action in your forked PR. I don't have a specific example to show you, but let me know if you can't find it.

2021-07-15 23:23 UTC, chrisgilmerproj commented
> For the GH actions permission error, there should be a setting to enable the action in your forked PR. I don't have a specific example to show you, but let me know if you can't find it.

I went ahead and ensured that actions are enabled on my fork of the repo. But it appears that's not enough. I did some searching and found this thread that indicates maybe a change is needed in the workflow? I could be wrong but its worth maybe checking out:

https://github.com/stefanzweifel/git-auto-commit-action/issues/114 

Let me know what you need me to do to get this rolling.

2021-08-03 20:40 UTC, dynamike-debug commented
Can you try merging changes from the `main` branch. It looks likes the terraform-docs action wasn't working, but was fixed after an update.

2021-08-03 20:41 UTC, dynamike commented
Can you try merging in changes from `main` into your fork? I think there was an issue with the terraform-docs github action, but it appears to be working now.

2021-08-03 20:56 UTC, chrisgilmerproj commented
@dynamike - I'm surprised this isn't working even after merging in `master`. I'm fairly certain I did the right thing too. Any thoughts on what's going on here? Are there odd permissions against the remote repo I can look into?

2021-08-03 21:03 UTC, dynamike commented
Yeah there are some rough edges to workout. The first place to check is the actions tab in your forked repo. There should be a button to enable actions on the forked repo. Something like `Workflows aren't being run on this forked repository`. 

If that doesn't work then I'd next look at a more dubious change around allowing edits by maintainers in the PR you submitted. 
![image](https://user-images.githubusercontent.com/675823/128085780-0b082f0b-40eb-492a-85d5-16ce344b2bb5.png)

2021-08-03 21:05 UTC, chrisgilmerproj commented
Here is my actions tab in the forked repo:

<img width="1421" alt="Screen Shot 2021-08-03 at 2 04 51 PM" src="https://user-images.githubusercontent.com/219296/128085996-6729fead-cd0d-4176-be07-0bbe4af373e7.png">

2021-08-03 21:12 UTC, dynamike commented
Multiple actions pages makes this a fun exercise. It should be under https://github.com/dod-iac/terraform-aws-bootstrap/actions

2021-08-03 21:17 UTC, chrisgilmerproj commented
Aha, I see how that was confusing. So I went to the tab and the workflow is enabled, it just never has run in my fork.

<img width="1437" alt="Screen Shot 2021-08-03 at 2 16 48 PM" src="https://user-images.githubusercontent.com/219296/128087392-85637147-79c8-4541-b995-dad08853c08d.png">

2021-08-03 21:40 UTC, dynamike commented
Thanks for debugging with me. That all looks correct. I think the next thing to look at is to allow edits and access to maintainers, because the logs say it's committing the terraform-docs change, but not able to push to your repo. If you aren't comfortable with that kind of a change, let me know.

2021-08-03 21:45 UTC, chrisgilmerproj commented
I'm ok with setting up the ability for the tool to push back. I am following this doc here:

https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

It says I ought to see a way to allow editing below the `Notifications` on the right side but here's what I'm seeing:

<img width="363" alt="Screen Shot 2021-08-03 at 2 44 50 PM" src="https://user-images.githubusercontent.com/219296/128090477-c619ee93-aca6-412b-99f7-1a7d0409f142.png">

I'm wondering if there is an organizational block I've not figured out yet.

2021-08-03 21:51 UTC, dynamike commented
That's likely it. This is what my debugging user interface looks like. I'm not sure what else to try at this point except maybe having the action just run on merges to `main`. It's an interesting edge case though. For now I'll merge and resolve the readme changes --

![image](https://user-images.githubusercontent.com/675823/128090908-73d8b56b-24e3-4553-bc82-be82606b704e.png)

2021-08-03 21:51 UTC, chrisgilmerproj commented
What an interesting find. Well, I guess I'm glad we at least tried. Thanks for helping me with this.

2021-08-03 21:52 UTC, merged